### ISSUE TITLE
Can't Build the Project from any location.

### ISSUE THREAD

**Issue by rasika2012** [ballerina-platform/ballerina-www#1015]
**Description:**
When the project is created on my usual projects location(some where in the drive),and couldn't able to build.there was no mistake.
It worked after change location to _/home/user/Desktop_ . 

**ballerina-internal.log**
[2018-07-12 16:36:54,804] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:39:22,399] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:41:49,665] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:42:43,291] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:45:47,105] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:47:24,497] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:48:54,750] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:50:47,086] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:53:40,763] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:54:36,415] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/user/calculator/0.1.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:56:53,892] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:57:24,866] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 16:58:16,452] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 
[2018-07-12 17:36:09,753] ERROR {org.ballerinalang.launcher.Main} - Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip 
java.lang.IllegalArgumentException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI.create(URI.java:852)
	at org.wso2.ballerinalang.compiler.FileSystemProjectDirectory.saveCompiledPackage(FileSystemProjectDirectory.java:165)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:153)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:125)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:89)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:96)
	at org.ballerinalang.packerina.BuilderUtils.compileAndWrite(BuilderUtils.java:54)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:94)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 26: jar:file:/media/user/New Volume/Project Non Academic/Ballerina/.ballerina/repo/$anon/calculator/0.0.0/calculator.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 9 more
 

**Suggested [Labels:**]
build

**Comment by vinok88** [comment]
This is happening since your file path has names with spaces. We will fix that. Thanks.

**Comment by NatashaWso2** [comment]
This issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9377 and the fix is available in [RC 0.980.0](https://ballerina.io/downloads/).  Closing this issue since this is fixed
